# Generated by Django 4.2.13 on 2024-06-26 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="train_station.route",
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="train_station.train",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="journey",
            field=models.ManyToManyField(
                blank=True, related_name="crews", to="train_station.journey"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("cargo", "seat", "journey")},
        ),
    ]
