# Generated by Django 4.2.13 on 2024-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
