# Generated by Django 4.2.13 on 2024-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0003_alter_route_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("destination", "source"), name="station_route"
            ),
        ),
    ]
