# Generated by Django 4.2.13 on 2024-06-29 21:36

from django.db import migrations, models
import train_station.models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0005_alter_train_train_type_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.get_image_path
            ),
        ),
    ]
